{% set name = "wireviz" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wireviz-{{ version }}.tar.gz
  sha256: 0e25ad8c2e3a269a7dd4a7f45e4e8d304db7e0432b1843a620acfa6be70570e1

build:
  entry_points:
    - wireviz=wireviz.wv_cli:wireviz
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click
    - pyyaml
    - pillow
    - python-graphviz

test:
  imports:
    - wireviz
  commands:
    - pip check
    - wireviz --help
  requires:
    - pip

about:
  home: https://github.com/formatc1702/WireViz
  summary: Easily document cables and wiring harnesses
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
